# Generated by Django 2.0.1 on 2018-03-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destinationID', models.AutoField(primary_key=True, serialize=False)),
                ('destinationName', models.CharField(max_length=255)),
                ('destinationType', models.CharField(max_length=255)),
                ('destinationDescription', models.CharField(max_length=255)),
                ('destinationCountry', models.CharField(max_length=255)),
                ('destinationState', models.CharField(max_length=255)),
                ('destinationAddress', models.CharField(max_length=255)),
                ('destinationCurrency', models.CharField(max_length=25)),
                ('destinationMinPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinationMaxPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinationMinTemp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinationMaxTemp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotelID', models.AutoField(primary_key=True, serialize=False)),
                ('hotelName', models.CharField(max_length=255)),
                ('hotelLocation', models.CharField(max_length=255)),
                ('hotelContact', models.IntegerField()),
                ('hotelCheckin', models.DateField(auto_now_add=True)),
                ('hotelCheckout', models.DateField(auto_now_add=True)),
                ('hotelDescription', models.CharField(max_length=255)),
                ('hotelImage', models.ImageField(max_length=255, upload_to=None)),
                ('hotelPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('destinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=10000)),
                ('destinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=10000)),
                ('hotelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVehicleRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='StarredDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred', models.BooleanField()),
                ('destinationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='StarredHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred', models.BooleanField()),
                ('hotelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='StarredVehicleRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRental',
            fields=[
                ('vehicleID', models.AutoField(primary_key=True, serialize=False)),
                ('vehicleCompany', models.CharField(max_length=255)),
                ('vehicleLocation', models.CharField(max_length=255)),
                ('vehicleType', models.CharField(max_length=255)),
                ('vehicleRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicleMileageAllowance', models.IntegerField()),
                ('vehicleBaseCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicleTotalCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicleCurrency', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='starredvehiclerental',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='starredvehiclerental',
            name='vehicleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.VehicleRental'),
        ),
        migrations.AddField(
            model_name='starredhotel',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='starreddestination',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
        migrations.AddField(
            model_name='reviewvehiclerental',
            name='vehicleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.VehicleRental'),
        ),
        migrations.AddField(
            model_name='history',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
