# Generated by Django 2.0.1 on 2018-03-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destinationCurrency',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destinationMaxPrice',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destinationMaxTemp',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destinationMinPrice',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='destinationMinTemp',
        ),
        migrations.AddField(
            model_name='destination',
            name='destinationPlaceID',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
