# Generated by Django 2.0.1 on 2018-03-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rating_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='userID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
            preserve_default=False,
        ),
    ]
