# Generated by Django 2.0.1 on 2018-04-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180324_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(max_length=255)),
                ('iata', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('elevation', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tz', models.CharField(max_length=255)),
            ],
        ),
    ]
