# Generated by Django 2.0.1 on 2018-04-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_airports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airports',
            new_name='Airport',
        ),
    ]
