# Generated by Django 2.0.1 on 2018-04-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20180412_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='lat',
            field=models.DecimalField(decimal_places=40, max_digits=50),
        ),
        migrations.AlterField(
            model_name='airport',
            name='lon',
            field=models.DecimalField(decimal_places=40, max_digits=50),
        ),
    ]
