# Generated by Django 2.0.1 on 2018-04-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20180412_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='tz',
        ),
    ]
