# Generated by Django 2.0.1 on 2018-04-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20180412_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelDescription',
            new_name='hotelCity',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelLocation',
            new_name='hotelCountry',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotelCheckin',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotelCheckout',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotelContact',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotelImage',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotelPrice',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelSabreID',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelStreet',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelZip',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
