# Generated by Django 2.0.1 on 2018-04-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20180416_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerental',
            old_name='vehicleLocation',
            new_name='vehicleCity',
        ),
        migrations.RenameField(
            model_name='vehiclerental',
            old_name='vehicleType',
            new_name='vehicleCountry',
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='vehicleBaseCost',
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='vehicleCurrency',
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='vehicleMileageAllowance',
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='vehicleRate',
        ),
        migrations.RemoveField(
            model_name='vehiclerental',
            name='vehicleTotalCost',
        ),
        migrations.AddField(
            model_name='vehiclerental',
            name='vehicleSabreID',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclerental',
            name='vehicleStreet',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclerental',
            name='vehicleZip',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
